# Generated by Django 5.2.7 on 2025-11-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "income_segment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "loyalty_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("total_spent", models.FloatField(blank=True, default=0, null=True)),
                (
                    "avg_order_value",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("total_orders", models.IntegerField(blank=True, default=0, null=True)),
                ("total_items", models.IntegerField(blank=True, default=0, null=True)),
                ("avg_discount", models.FloatField(blank=True, default=0, null=True)),
                (
                    "avg_review_rating",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "avg_seller_rating",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "avg_delivery_days",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "total_returns",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("return_ratio", models.FloatField(blank=True, default=0, null=True)),
                (
                    "total_previous_returns",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("is_prime_member", models.BooleanField(default=False)),
                (
                    "customer_tenure_days",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("last_order_date", models.DateField(blank=True, null=True)),
                ("first_order_date", models.DateField(blank=True, null=True)),
                ("recency_days", models.FloatField(blank=True, default=0, null=True)),
                ("tenure_days", models.FloatField(blank=True, default=0, null=True)),
                ("frequency", models.FloatField(blank=True, default=0, null=True)),
                ("predicted_clv", models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientNewsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("birthday", "Birthday"), ("risk", "At-Risk Client")],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "message",
                    models.TextField(
                        help_text="Use placeholders like {name}, {region}, {discount}"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100, unique=True)),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("discounted_price", models.FloatField()),
                ("actual_price", models.FloatField()),
                ("discount_percentage", models.FloatField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("rating_count", models.IntegerField(default=0)),
                ("about_product", models.TextField(blank=True, null=True)),
                ("stock", models.IntegerField(default=0)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("last_updated_date", models.DateField(auto_now=True)),
                ("status", models.CharField(default="active", max_length=50)),
            ],
        ),
    ]
