# Generated by Django 3.2.25 on 2025-10-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('E-Shop', 'E-Shop'), ('Mobile App', 'Mobile App'), ('Manual', 'Manual')], max_length=50)),
                ('loyalty_status', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=20)),
                ('clv', models.FloatField(default=0.0)),
            ],
        ),
    ]
