# Generated by Django 3.2.25 on 2025-10-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [

        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='avg_delivery_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='avg_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='avg_order_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='avg_review_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='avg_seller_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_tenure_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='first_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='income_segment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_prime_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='last_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='recency_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='return_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='tenure_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='total_previous_returns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='total_returns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='total_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='loyalty_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
