# Generated by Django 3.2.25 on 2025-10-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20251025_1253'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='client',
            name='clv',
        ),
    ]
