# Generated by Django 3.2.25 on 2025-10-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20251025_1401'),
    ]

    operations = [

        migrations.AddField(
            model_name='client',
            name='clv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
