# Generated by Django 3.2.25 on 2025-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20251025_1456'),
    ]

    operations = [

        migrations.RenameField(
            model_name='client',
            old_name='clv',
            new_name='predicted_clv',
        ),
    ]
