# Generated by Django 3.2.25 on 2025-10-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20251026_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('discounted_price', models.FloatField()),
                ('actual_price', models.FloatField()),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(default=0)),
                ('about_product', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
        ),
    ]
